name: Check exports

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-exports:
    name: Check exports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Harden runner
        uses: ./.github/actions/harden-runner
      - name: Install pnpm and setup Node.js
        uses: ./.github/actions/pnpm-node
      - name: Install TypeScript
        run: pnpm add typescript
      - name: Install @arethetypeswrong/cli
        run: pnpm add @arethetypeswrong/cli
      - name: Run check-exports
        run: pnpm check-exports
